---
- hosts: all
  become: yes
  gather_facts: no
  vars:
      source_path: ./source
      target_path: /home/johndoe/apps/app1
  
  tasks: 
  - name: Run the equivalent of "apt-get update" as a separate step
    apt:
     update_cache: yes
  
  - name: Install system packages
    apt: name={{ item }} state=present
    with_items:
      - git
      - nodejs
      - npm
      - nginx

  # copy local files without git  
  #  - name: Copy source files
  #    ansible.builtin.copy:
  #      src: "{{ source_path }}"
  #      dest: "{{ target_path }}"

  - name: Clone a repo from a 3rd party github server
    ansible.builtin.git:
      repo: https://github.com/daedalus1948/ansible_test_public
      dest: "{{ target_path }}"

  - name: Install nodejs packages based on package.json.
    community.general.npm:
      path: /home/johndoe/apps/app1/source

  - name: Copy systemd service file to target system location
    ansible.builtin.copy:
      src: ./express_app_test.service
      dest: /etc/systemd/system/express_app_test.service


  - name: Delete default nginx vhost symlink
    file: path=/etc/nginx/sites-enabled/default state=absent

  - name: Add new nginx conf file
    ansible.builtin.copy:
      src: ./node_app_nginx.conf
      dest: /etc/nginx/sites-available/node_app_nginx.conf


  - name: Setup a new symlink with the previously copied configuration
    file: src=/etc/nginx/sites-available/node_app_nginx.conf
      dest=/etc/nginx/sites-enabled/node_app_nginx.conf
      state=link

  - name: Start express_app_test systemd service and verify
    ansible.builtin.systemd:
      name: express_app_test
      enabled: yes
      state: restarted

  - name: Verify if nginx systemd service re/started
    ansible.builtin.systemd:
      name: nginx
      enabled: yes
      state: restarted

  - name: configure ufw - allow port 80 for nginx (later use ufw app profiles to allow nginx this way)
    community.general.ufw:
      rule: allow
      port: 80
      proto: tcp

  - name: enable universal firewall UFW
    community.general.ufw:
      state: enabled
